export enum ConfigEndpoints {
  isFeatureFlagEnabled = 'reference-data/config/isFeatureFlagEnabled',
  getExchangeHoldingsWallets = 'reference-data/config/getExchangeHoldingsWallets',
  getTransactionFeeCaps = 'reference-data/config/getTransactionFeeCaps',
  getExchangeDepositPollingFrequency = 'reference-data/config/getExchangeDepositPollingFrequency',
  getVatRate = 'reference-data/config/getVatRate',
  getWithdrawalConfigForCurrency = 'reference-data/config/getWithdrawalConfigForCurrency',
  updateWithdrawalConfigForCurrency = 'reference-data/config/updateWithdrawalConfigForCurrency',
  getWithdrawalConfig = 'reference-data/config/getWithdrawalConfig',
  getWithdrawalLimit = 'reference-data/config/getWithdrawalLimit',
  getOperationsEmail = 'reference-data/config/getOperationsEmail',
  getEthereumDepositMaxBlockCheck = 'reference-data/config/getEthereumDepositMaxBlockCheck',
  getExcludedAccountTypesFromOrderRangeValidations = 'reference-data/config/getExcludedAccountTypesFromOrderRangeValidations',
  getDepositMimimumAmounts = 'reference-data/config/getDepositMimimumAmounts',
}
