language: node_js
node_js:
  - '10.13'
addons:
  apt:
    packages:
      - docker-ce
  hosts:
    - 127.0.0.1 redis
    - 127.0.0.1 local.kinesisgroup.io
  postgresql: '9.6'
services:
  - docker
  - redis-server
  - postgresql
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
notifications:
  email: false
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set profile.kinesis.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set profile.kinesis.aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set profile.kinesis.region ap-southeast-2
  - gem install bundler --version '2.0.2'
before_script:
  - PGPASSWORD=postgres psql -c 'create database kinesis_exchange;' -U postgres

jobs:
  include:
    # Build builds execute tests for changed functional areas and upon success create a new ${BRANCH_NAME}-{COMMIT_HASH} image tag, uploaded to ECR
    # !!!! ONLY FOR THE SERVICES WHERE THERE WERE CHANGES
    - stage: Build & Deploy
      script: ./_scripts/travis/travis-build-feature-or-bugfix.sh '{@abx/exchange-deposit-service,@abx/exchange-reference-data-service}'
      name: Build & Test Deposit and Reference Data Functional Areas
    - script: ./_scripts/travis/travis-build-feature-or-bugfix.sh '{@abx/exchange-withdrawal-service,@abx/exchange-balance-service}'
      name: Build & Test Withdrawal and Balance Functional Areas
    - script: ./_scripts/travis/travis-build-feature-or-bugfix.sh '{@abx/exchange-scheduler-service,@abx/exchange-reports-service,@abx/exchange-account-data-service}'
      name: Build & Test Scheduler, Reports and Account Functional Areas
    - script: ./_scripts/travis/travis-build-feature-or-bugfix.sh '{@abx/exchange-notification-service,@abx/admin-fund-management-service}'
      name: Build & Test Notification and Admin Fund Management Functional Areas
    - script: ./_scripts/travis/travis-build-feature-or-bugfix.sh '{@abx/order-service,@abx/exchange-market-data-service}'
      name: Build & Test Order and Market Data Functional Areas
    - stage: Deploy
      if: (branch =~ /^bugfix*/ or branch =~ /^feature*/) and type = push
      script: ./_scripts/travis/travis-release-image-feature-or-bugfix.sh '{@abx/exchange-deposit-service,@abx/exchange-reference-data-service}'
      name: Deploy Deposit and Reference Data Functional Areas
      if: (branch =~ /^bugfix*/ or branch =~ /^feature*/) and type = push
    - script: ./_scripts/travis/travis-release-image-feature-or-bugfix.sh '{@abx/exchange-withdrawal-service,@abx/exchange-balance-service}'
      name: Deploy Withdrawal and Balance Functional Areas
      if: (branch =~ /^bugfix*/ or branch =~ /^feature*/) and type = push
    - script: ./_scripts/travis/travis-release-image-feature-or-bugfix.sh '{@abx/exchange-scheduler-service,@abx/exchange-reports-service,@abx/exchange-account-data-service}'
      name: Deploy Scheduler, Reports and Account Functional Areas
      if: (branch =~ /^bugfix*/ or branch =~ /^feature*/) and type = push
    - script: ./_scripts/travis/travis-release-image-feature-or-bugfix.sh '{@abx/exchange-notification-service,@abx/admin-fund-management-service}'
      name: Deploy Notification and Admin Fund Management Functional Areas
      if: (branch =~ /^bugfix*/ or branch =~ /^feature*/) and type = push
    - script: ./_scripts/travis/travis-release-image-feature-or-bugfix.sh '{@abx/order-service,@abx/exchange-market-data-service}'
      name: Deploy Order and Market Data Functional Areas
      if: (branch =~ /^bugfix*/ or branch =~ /^feature*/) and type = push
    - stage: API Docs update
      if: tag IS present
      script:
        - npm run bootstrap:production
        - npm run build
        - cd packages/services/_api-docs
        - bundle install
        - npm run build:docs
        - npm run push-api-docs-to-s3
