language: node_js
node_js:
  - '10.13'
addons:
  apt:
    packages:
      - docker-ce
  hosts:
    - 127.0.0.1 redis
    - 127.0.0.1 local.kinesisgroup.io
  postgresql: '9.6'
services:
  - docker
  - redis-server
  - postgresql
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set profile.kinesis.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set profile.kinesis.aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set profile.kinesis.region ap-southeast-2
  - gem install bundler --version '2.0.2'
before_script:
  - psql -c 'create database kinesis_exchange;' -U postgres
  - npm link
  - npm run bootstrap
  - lerna run build --scope @abx-utils/kbe-legacy-migrations --include-dependencies --exclude-dependents
  - npm run run-legacy-migrations:test

jobs:
  include:
    #The following scripts trigger parallel test runs for the different functional areas
    # !!!! ONLY FOR THE SERVICES WHERE THERE WERE CHANGES
    - script: lerna run test --scope @abx/exchange-deposit-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Deposit Functional Area
    - script: lerna run test --scope @abx/exchange-withdrawal-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Withdrawal Functional Area
    - script: lerna run test --scope @abx/exchange-balance-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Balance Functional Area
    - script: lerna run test --scope @abx/exchange-reference-data-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Reference Data Functional Area
    - script: lerna run test --scope @abx/exchange-reports-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Reports Data Functional Area
    - script: lerna run test --scope @abx/exchange-scheduler-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Scheduler Data Functional Area
    - script: lerna run test --scope @abx/exchange-notification-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Notification Data Functional Area
    - script: lerna run test --scope @abx/admin-fund-management-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Admin Fund Management Functional Area
    - script: lerna run test --scope @abx/order-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Order Data Functional Area
    - script: lerna run test --scope @abx/exchange-market-data-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Market Data Functional Area
    - script: lerna run test --scope @abx/exchange-account-data-service --since develop --include-dependencies
      if: tag IS blank and branch != develop
      name: Build & Test Account Functional Area

      #The following scripts trigger parallel image build for the different functional areas
      # !!!! ONLY FOR THE SERVICES WHERE THERE WERE CHANGES
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-balance-service
      if: branch = develop and type = push
      name: 'Build Balance image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-reference-data-service
      if: branch = develop and type = push
      name: 'Build Reference Data image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-report-service
      if: branch = develop and type = push
      name: 'Build Reports image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-scheduler-service
      if: branch = develop and type = push
      name: 'Build Scheduler image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-withdrawal-service
      if: branch = develop and type = push
      name: 'Build Withdrawal image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-notification-service
      if: branch = develop and type = push
      name: 'Build Notification image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/order-service
      if: branch = develop and type = push
      name: 'Build Order image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-market-data-service
      if: branch = develop and type = push
      name: 'Build Market Data image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-deposit-service
      if: branch = develop and type = push
      name: 'Build Deposit image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/admin-fund-management-service
      if: branch = develop and type = push
      name: 'Build admin fund management image and push to ECR'
    - script: ./_scripts/travis/travis-build-service-release.sh @abx/exchange-account-data-service
      if: branch = develop and type = push
      name: 'Build Account image and push to ECR'

    # Triggered after a push to develop branch, generating the latest API documentation
    - script:
        - npm run bootstrap:production
        - npm run build
        - cd packages/services/_api-docs
        - bundle install
        - npm run build:docs
        - npm run push-api-docs-to-s3
      if: branch = develop and type = push
      name: 'Build latest api docs and push to s3'
