version: '3.3'
volumes:
  - postgres-data:/var/lib/postgres/data
services:
  redis:
    image: redis
    container_name: redis-dev
    ports:
      - '7379:6379'
  postgres:
    image: postgres:9.6
    container_name: postgres-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kinesis_exchange
volumes:
  postgres-data:
