version: '3.3'
services:
  redis:
    image: redis
    container_name: redis-dev
    ports:
      - '7379:6379'
  postgres:
    image: postgres:9.6
    container_name: postgres-dev
    volumes:
      - ./data/postgres-exchange-2:/var/lib/postgresql/data
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kinesis_exchange
  debit-card-postgres:
    image: postgres:9.6
    container_name: debit-card-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
